project_name = "nurd_validation"
seed = 1
load_it = "best"
batch_size = 64
num_epochs = 1000
sort_context = false
lr = 0.001
decay_lr = 10
train_split = "train"
val_split = "val"
n_trials = 1
beta = 1
reweight = false
dataset = "nurd"
knowledge_type = "none"
min_num_context = 0
max_num_context = 10
num_targets = 1000
noise = 0.0
x_sampler = "uniform"
use_knowledge = false
text_encoder = "set"
freeze_llm = true
tune_llm_layer_norms = false
train_num_z_samples = 1
test_num_z_samples = 16
knowledge_dropout = 0.3
input_dim = 1
output_dim = 1
hidden_dim = 1
xy_encoder_num_hidden = 1
xy_encoder_hidden_dim = 16
xy_self_attention = "none"
xy_self_attention_num_layers = 1
data_agg_func = "mean"
latent_encoder_num_hidden = 1
decoder_hidden_dim = 16
decoder_num_hidden = 1
decoder_activation = "gelu"
x_transf_dim = 1
x_encoder_num_hidden = 1
path = "latent"
knowledge_extractor_num_hidden = 2
knowledge_extractor_hidden_dim = 1
knowledge_merge = "sum"
knowledge_dim = 1
run_name_prefix = "nurd_validation"
run_name_suffix = "tuned"
